---
- name: Configure monitoring services

  hosts: localhost

  vars:

  pre_tasks:

    - name: Check for dependent python modules
      community.general.python_requirements_info:
        dependencies:
          - docker>=5.0.0
      tags:
        - always

    # - name: create configuration directory for user
    #   ansible.builtin.user:
    #     name: "{{ ansible_user_id }}"
    #     state: present
    #   register: ansible_user_registered
    #   tags:
    #     - always

    # Need to check whether installed and skip
    # https://grafana.com/docs/loki/latest/clients/docker-driver/
    - name: Install docker driver
      ansible.builtin.command: docker plugin install grafana/loki-docker-driver:latest --alias loki --grant-all-permissions
      register: docker_driver_loki
      when: 0

    - name: Run message
      ansible.builtin.debug:
        msg: "Running on host {{ ansible_hostname }} via {{ ansible_default_ipv4.interface }} @ {{ ansible_default_ipv4.address }} as user {{ ansible_user_id }}"
      tags:
        - always

  tasks:

    ####### MONITORING NETWORK SECTION

    # Based on
    # https://community.home-assistant.io/t/how-to-run-homeassistant-on-docker-on-its-own-network-instead-of-the-host-network/189315/4

    - name: Set Monitoring Network facts
      ansible.builtin.set_fact:
        monitoring_network_name: monitoring-network

    - name: Create a Monitoring Network
      community.docker.docker_network:
        name: "{{ monitoring_network_name | default('monitoring_network') }}"
        internal: false
    
    ####### NODE EXPORTER SECTION

    - name: Set Node Exporter facts
      ansible.builtin.set_fact:
        node_exporter_image_name: prom/node-exporter
        node_exporter_image_tag: latest
        node_exporter_container_name: node-exporter
        node_exporter_container_port: 9100
      tags:
        - node-exporter

    - name: Check if Node Exporter is running
      community.docker.docker_container_info:
        name: "{{ node_exporter_container_name }}"
      register: node_exporter_state
      
    - block:

      - name: Pull Node Exporter image
        community.docker.docker_image:
          name: "{{ node_exporter_image_name }}:{{ node_exporter_image_tag | default('latest') }}"
          source: pull
        tags:
          - node-exporter

      - name: Start Node Exporter
        community.docker.docker_container:
          name: "{{ node_exporter_container_name }}"
          image: "{{ node_exporter_image_name }}:{{ node_exporter_image_tag | default('latest') }}"
          detach: true
          networks_cli_compatible: true
          networks:
            - name: "{{ monitoring_network_name }}"
          published_ports:
            - "{{ node_exporter_container_port }}:9100"
          restart_policy: unless-stopped
          state: started
          volumes:
            - /proc:/host/proc:ro
            - /sys/:/host/sys:ro
            - /:/rootfs:ro
        register: node_exporter_register
        tags:
          - node-exporter

      - name: Wait for Node Exporter to accept connections
        ansible.builtin.wait_for:
          # host: "{{ node_exporter_register['container']\
          #   ['NetworkSettings']\
          #   ['Networks']\
          #   ['monitoring-network']\
          #   ['IPAddress'] }}"
          host: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
          port: "{{ node_exporter_container_port | default(9100) }}"
          connect_timeout: 1
          delay: 10
          state: started
          timeout: 30
        register: node_exporter_running
        until: node_exporter_running is success
        retries: 10
        tags:
          - node-exporter

      when: not node_exporter_state.exists

    ####### LOKI SECTION

    # Source: https://grafana.com/docs/loki/latest/installation/docker/

    - name: Set Loki facts
      ansible.builtin.set_fact:
        loki_image_name: grafana/loki
        loki_image_tag: 2.6.1
        loki_container_name: loki
        loki_container_port: 3100
        loki_config_dir: "/home/{{ ansible_user_id }}"
        loki_volume: loki-volume
      tags:
        - loki

    - name: Check if Loki is running
      community.docker.docker_container_info:
        name: "{{ loki_container_name }}"
      register: loki_state
      tags:
        - loki
      
    - block:
    
      - name: Pull Loki image
        community.docker.docker_image:
          name: "{{ loki_image_name }}:{{ loki_image_tag | default('latest') }}"
          source: pull
        tags:
          - loki

      # wget https://raw.githubusercontent.com/grafana/loki/v2.6.1/cmd/loki/loki-local-config.yaml -O loki-config.yaml
      - name: Pull Loki configuration
        ansible.builtin.get_url:
          url: "https://raw.githubusercontent.com/grafana/loki/v{{ loki_image_tag }}/cmd/loki/loki-local-config.yaml"
          dest: "{{ loki_config_dir }}/loki-config.yaml"
        tags:
          - loki

      # docker run --name loki -d -v $(pwd):/mnt/config -p 3100:3100 grafana/loki:2.6.1 -config.file=/mnt/config/loki-config.yaml
      - name: Start Loki
        community.docker.docker_container:
          name: "{{ loki_container_name }}"
          image: "{{ loki_image_name }}:{{ loki_image_tag | default('latest') }}"
          command: --config.file=/mnt/config/loki-config.yaml
          detach: true
          networks_cli_compatible: true
          networks:
            - name: "{{ monitoring_network_name }}"
          published_ports:
            - "{{ loki_container_port }}:3100"
          restart: true
          restart_policy: unless-stopped
          state: started
          volumes:
            - "{{ loki_config_dir }}:/mnt/config"
            - /etc/localtime:/etc/localtime:ro
        register: loki_register
        tags:
          - loki

      - name: Wait for Loki to accept connections
        ansible.builtin.wait_for:
          # host: "{{ loki_register['container']\
          #   ['NetworkSettings']\
          #   ['Networks']\
          #   ['monitoring-network']\
          #   ['IPAddress'] }}"
          host: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
          port: "{{ loki_container_port | default(3100) }}"
          connect_timeout: 1
          delay: 10
          state: started
          timeout: 30
        register: loki_running
        until: loki_running is success
        retries: 10
        tags:
          - loki

      when: not loki_state.exists

    ####### PROMTAIL SECTION

    # Source: https://grafana.com/docs/loki/latest/installation/docker/

    - name: Set Promtail facts
      ansible.builtin.set_fact:
        promtail_image_name: grafana/promtail
        promtail_image_tag: "{{ loki_image_tag | default('latest') }}"
        promtail_container_name: promtail
        promtail_config_dir: "/home/{{ ansible_user_id }}"
      tags:
        - promtail

    - name: Check if Promtail is running
      community.docker.docker_container_info:
        name: "{{ promtail_container_name }}"
      register: promtail_state
      tags:
        - promtail
      
    - block:
    
      - name: Pull Promtail image
        community.docker.docker_image:
          name: "{{ promtail_image_name }}:{{ promtail_image_tag | default('latest') }}"
          source: pull
        tags:
          - promtail

      # wget https://raw.githubusercontent.com/grafana/loki/v2.6.1/clients/cmd/promtail/promtail-docker-config.yaml -O promtail-config.yaml
      - name: Pull Promtail configuration
        ansible.builtin.get_url:
          url: "https://raw.githubusercontent.com/grafana/loki/v{{ loki_image_tag }}/clients/cmd/promtail/promtail-docker-config.yaml"
          dest: "{{ promtail_config_dir }}/promtail-config.yaml"
        tags:
          - promtail

      # docker run --name promtail -d -v $(pwd):/mnt/config -v /var/log:/var/log --link loki grafana/promtail:2.6.1 -config.file=/mnt/config/promtail-config.yaml
      - name: Start Loki
        community.docker.docker_container:
          name: "{{ promtail_container_name }}"
          image: "{{ promtail_image_name }}:{{ promtail_image_tag | default('latest') }}"
          command: --config.file=/mnt/config/promtail-config.yaml
          detach: true
          links:
            - loki:loki
          networks_cli_compatible: true
          networks:
            - name: "{{ monitoring_network_name }}"
          restart: true
          restart_policy: unless-stopped
          state: started
          volumes:
            - "{{ promtail_config_dir }}:/mnt/config"
            - /var/log:/var/log
            - /etc/localtime:/etc/localtime:ro
        register: promtail_register
        tags:
          - promtail

      when: not promtail_state.exists

    ####### PROMETHEUS SECTION

    # https://hub.docker.com/r/prom/prometheus
    # https://medium.com/platform-engineering/monitoring-traefik-with-grafana-1d037af5b952

    - name: Set Prometheus facts
      ansible.builtin.set_fact:
        prometheus_image_name: prom/prometheus
        prometheus_image_tag: latest
        prometheus_container_name: prometheus
        prometheus_container_port: 9090
      tags:
        - prometheus

    - name: Check if Prometheus is running
      community.docker.docker_container_info:
        name: "{{ prometheus_container_name }}"
      register: prometheus_state
      
    - block:

      - name: Pull Prometheus image
        community.docker.docker_image:
          name: "{{ prometheus_image_name }}:{{prometheus_image_tag | default('latest') }}"
          source: pull
        tags:
          - prometheus

      - name: Start Prometheus
        community.docker.docker_container:
          name: "{{ prometheus_container_name | default('prometheus') }}"
          image: "{{ prometheus_image_name }}:{{ prometheus_image_tag | default('latest') }}"
          command:
            - --config.file=/etc/prometheus/prometheus.yml
            - --web.enable-lifecycle
          detach: true
          memory: 300M
          memory_reservation: 100M
          networks_cli_compatible: true
          networks:
            - name: "{{ monitoring_network_name }}"
          published_ports:
            - "{{ prometheus_container_port | default(9090) }}:9090"
          state: started
          recreate: true
          restart: true
          restart_policy: unless-stopped
          volumes:
            # - "/home/{{ ansible_user }}/prometheus.yml:/etc/prometheus/prometheus.yml:ro"
            - /etc/localtime:/etc/localtime:ro
        register: prometheus_register
        tags:
          - prometheus

      - name: Wait for Prometheus to accept connections
        ansible.builtin.wait_for:
          # host: "{{ prometheus_register['container']\
          #   ['NetworkSettings']\
          #   ['Networks']\
          #   ['monitoring-network']\
          #   ['IPAddress'] }}"
          host: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
          port: "{{ prometheus_container_port | default('9090') }}"
          connect_timeout: 1
          delay: 10
          state: started
          timeout: 30
        register: prometheus_running
        until: prometheus_running is success
        retries: 10
        tags:
          - prometheus

      when: not prometheus_state.exists

    - name: Add Prometheus container to inventory
      add_host:
        name: "{{ prometheus_container_name }}"
        ansible_connection: community.docker.docker
      changed_when: false
      when: 0

    - name: run command in container
      delegate_to: "{{ prometheus_container_name }}"
      copy:
        src: files/prometheus/prometheus.yml
        dest: /etc/prometheus/prometheus.yml
      when: 0

    - name: Copy configuration file into Prometheus container
      ansible.builtin.shell: docker cp files/prometheus/prometheus.yml {{ prometheus_container_name }}:/etc/prometheus/prometheus.yml
      tags:
        - prometheus

      # curl -X POST :9090/-/reload
    - name: Restart Prometheus via curl
      ansible.builtin.uri:
        url: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:9090/-/reload"
        method: POST
      tags:
        - prometheus

    ####### GRAFANA SECTION

    - name: Set Grafana facts
      ansible.builtin.set_fact:
        grafana_image_name: grafana/grafana
        grafana_image_tag: latest
        grafana_container_name: grafana
        grafana_container_port: 3000
        grafana_volume: grafana-volume
      tags:
        - grafana

    - name: Set Grafana facts
      ansible.builtin.set_fact:
        grafana_instance: grafana
        grafana_api_url: "http://{{ ansible_default_ipv4.address }}:{{ grafana_container_port }}"
        grafana_security: {admin_user: admin, admin_password: "monitoring"}
        grafana_use_provisioning: false  # will use API
      tags:
        - grafana

    - name: Create Grafana volume
      community.docker.docker_volume:
        name: "{{ grafana_volume }}"
        state: present
      tags:
        - grafana

    - name: Check if Grafana is running
      community.docker.docker_container_info:
        name: "{{ grafana_container_name }}"
      register: grafana_state

    - block:

      - name: Pull Grafana image
        community.docker.docker_image:
          name: "{{ grafana_image_name }}:{{ grafana_image_tag | default('latest') }}"
          source: pull
        tags:
          - grafana

      # docker run -d -p 3000:3000 grafana/grafana
      - name: Start Grafana
        community.docker.docker_container:
          name: "{{ grafana_container_name }}"
          image: "{{ grafana_image_name }}:{{ grafana_image_tag | default('latest') }}"
          detach: true
          env:
            GF_SECURITY_ADMIN_PASSWORD: "{{ grafana_security.admin_password }}"
            GF_USERS_ALLOW_SIGN_UP: "false"
          # log_driver: loki
          # log_options:
          #   loki-url: "http://{{ loki_container_name }}:{{ loki_container_port }}/loki/api/v1/push"
          #   loki-external-labels: job=dockerlogs,owner=monitor,environment=development
          networks_cli_compatible: true
          networks:
            - name: "{{ monitoring_network_name }}"
          published_ports:
            - "{{ grafana_container_port }}:3000"
          restart: true
          restart_policy: unless-stopped
          state: started
          # user: "{{ ansible_user_uid }}:{{ ansible_user_gid }}"
          volumes:
            - "{{ grafana_volume }}:/var/lib/grafana"
            - /etc/localtime:/etc/localtime:ro
        register: grafana_register
        tags:
          - grafana

      - name: Wait for Grafana to accept connections
        ansible.builtin.wait_for:
          # host: "{{ grafana_register['container']\
          #   ['NetworkSettings']\
          #   ['Networks']\
          #   ['monitoring-network']\
          #   ['IPAddress'] }}"
          host: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
          port: "{{ grafana_container_port | default('3000') }}"
          connect_timeout: 1
          delay: 10
          state: started
          timeout: 30
        register: grafana_running
        until: grafana_running is success
        retries: 10
        tags:
          - grafana

      when: not grafana_state.exists

    - name: Create Grafana datasources
      community.grafana.grafana_datasource:
        name: "{{ item.name }}"
        grafana_url: "{{ grafana_api_url }}"
        grafana_user: "{{ grafana_security.admin_user }}"
        grafana_password: "{{ grafana_security.admin_password }}"
        org_id: "1"
        ds_type: "{{ item.type }}"
        ds_url: "{{ item.url }}"
        access: "{{ item.access }}"
        tls_skip_verify: true
      with_items: "{{ grafana_datasources }}"
      vars:
        grafana_datasources:
          - name: Prometheus
            type: prometheus
            access: proxy
            url: "http://{{ prometheus_container_name }}:{{ prometheus_container_port }}"
            basicAuth: false
          - name: Loki
            type: loki
            access: proxy
            url: "http://{{ loki_container_name }}:{{ loki_container_port }}"
            basicAuth: false
          # - name: InfluxDB
          #   type: influxdb
          #   access: proxy
          #   url: "http://192.168.1.186:8086/"
          #   basicAuth: false
      tags:
        - grafana

    - name: Create Grafana dashboards
      community.grafana.grafana_dashboard:
        grafana_url: "{{ grafana_api_url }}"
        # grafana_api_key: "{{ grafana_api_key }}"
        grafana_user: "{{ grafana_security.admin_user }}"
        grafana_password: "{{ grafana_security.admin_password }}"
        # folder: General
        dashboard_url: "https://grafana.com/api/dashboards/{{ item.dashboard_id }}/revisions/{{ item.dashboard_revision }}/download"
      vars:
        grafana_dashboards:
          # Node Exporter Full by rfraile
          # https://grafana.com/grafana/dashboards/1860
          - dashboard_id: '1860'
            dashboard_revision: '27'
            datasource: 'Prometheus'
          # Loki Logs Dashboard by swaml
          # https://grafana.com/grafana/dashboards/15324
          - dashboard_id: '15324'
            dashboard_revision: '1'
            datasource: 'Loki'
          # Loki2.0 Global Metrics by Link
          # https://grafana.com/grafana/dashboards/13407
          - dashboard_id: '13407'
            dashboard_revision: '1'
            datasource: 'Loki'
      with_items: "{{ grafana_dashboards }}"
      tags:
        - grafana
